package graphics;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.HashSet;
import javax.swing.JFileChooser;
import object.FilePathConfiguration;
import singleton.ConfigurationManager;
import utils.DatabaseTableInserter;
import utils.MasterFileCreater;
import utils.TableCreater;
import utils.Utils;

/**
 *
 * @author MSHAO1
 */
public class DataParserPanel extends javax.swing.JPanel {

    /**
     * Creates new form DataParserPanel
     */
    public DataParserPanel() {
        initComponents();
    }

    private boolean validateGTFilePath() {
        if (filePathTextField.getText().equals("")) {
            Utils.displayWarningMessage(this, "Please select directory first!");
            return false;
        }
        if (!Files.exists(Paths.get(filePathTextField.getText() + "\\data"))) {
            consoleDisplayTextArea.append("Error: no 'data' path under root!\n");
            Utils.displayErrorMessage(this, "Error: no 'data' path under root!\n");
            return false;
        }
        return true;
    }

    private boolean validateMFFilePath() {
        if (filePathTextField.getText().equals("")) {
            Utils.displayWarningMessage(this, "Please select directory first!");
            return false;
        }
        if (!Files.exists(Paths.get(filePathTextField.getText() + "\\data\\movementFeatures.csv"))) {
            consoleDisplayTextArea.append("Error: no movementFeatures.csv under data folder!\n");
            Utils.displayErrorMessage(this, "Error: no movementFeatures.csv under data folder!\n");
            return false;
        } else if (!Files.exists(Paths.get(filePathTextField.getText() + "\\matlab\\AllFeatures.csv"))) {
            consoleDisplayTextArea.append("Error: no AllFeatures.csv under matlab folder!\n");
            Utils.displayErrorMessage(this, "Error: no AllFeatures.csv under matlab folder!\n");
            return false;
        }
        consoleDisplayTextArea.setText("");
        return true;
    }

    private boolean validateDPFilePath() {
        if (filePathTextField.getText().equals("")) {
            Utils.displayWarningMessage(this, "Please select directory first!");
            return false;
        }
        File folder = new File(filePathTextField.getText());
        File[] listOfFiles = folder.listFiles();
        HashSet<String> hSet = new HashSet<>();
        for (int i = 0; i < listOfFiles.length; i++) {
            if (listOfFiles[i].isFile()) {
                hSet.add(listOfFiles[i].getName());
            }
        }

        if (hSet.size() < 17) {
            consoleDisplayTextArea.append("Error: no 17 tables under current folder!\n");
            Utils.displayErrorMessage(this, "Error: no 17 tables under current folder!\n");
            return false;
        }

        for (String s : ConfigurationManager.getConfigurationManager().getDPConfiguration().getTABLE_NAMES()) {
            if (!hSet.contains(s + ".csv")) {
                consoleDisplayTextArea.append("Error: no " + s + " file under data folder!\n");
                Utils.displayErrorMessage(this, "Error: no " + s + " file under data folder!\n");
                return false;
            }
        }
        consoleDisplayTextArea.setText("");
        return true;
    }

    private void setupFileConfiguration(FilePathConfiguration fc, String filePath) {
        String[] filePathComponents = filePath.split("\\\\");
        if (filePathComponents.length > 0) {
            String cName = filePathComponents[filePathComponents.length - 1];
            fc.setAllPaths(filePath, cName);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consoleDisplayScrollPane = new javax.swing.JScrollPane();
        consoleDisplayTextArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        filePathTextField = new javax.swing.JTextField();
        mfPathButton = new javax.swing.JButton();
        mfGenerationButton = new javax.swing.JButton();
        outputHeadersCheckBox = new javax.swing.JCheckBox();
        tableGenerationButton = new javax.swing.JButton();
        uploadIntoDBButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(820, 540));
        setMinimumSize(new java.awt.Dimension(820, 540));

        consoleDisplayTextArea.setColumns(20);
        consoleDisplayTextArea.setRows(5);
        consoleDisplayTextArea.setFocusable(false);
        consoleDisplayScrollPane.setViewportView(consoleDisplayTextArea);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setMaximumSize(new java.awt.Dimension(800, 65));
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 65));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 65));

        jLabel3.setText("Dataset Path");

        filePathTextField.setFocusable(false);
        filePathTextField.setMaximumSize(new java.awt.Dimension(240, 20));
        filePathTextField.setMinimumSize(new java.awt.Dimension(240, 20));
        filePathTextField.setPreferredSize(new java.awt.Dimension(240, 20));

        mfPathButton.setText("Browse");
        mfPathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfPathButtonActionPerformed(evt);
            }
        });

        mfGenerationButton.setText("Generate Master File");
        mfGenerationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfGenerationButtonActionPerformed(evt);
            }
        });

        outputHeadersCheckBox.setText("Output with Headers");
        outputHeadersCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputHeadersCheckBoxActionPerformed(evt);
            }
        });

        tableGenerationButton.setText("Generate 17 Tables");
        tableGenerationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableGenerationButtonActionPerformed(evt);
            }
        });

        uploadIntoDBButton.setText("Upload Into DB");
        uploadIntoDBButton.setAutoscrolls(true);
        uploadIntoDBButton.setMaximumSize(new java.awt.Dimension(150, 23));
        uploadIntoDBButton.setMinimumSize(new java.awt.Dimension(150, 23));
        uploadIntoDBButton.setPreferredSize(new java.awt.Dimension(150, 23));
        uploadIntoDBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadIntoDBButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(filePathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(mfPathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(mfGenerationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uploadIntoDBButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tableGenerationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputHeadersCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(321, 321, 321))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filePathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mfPathButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(outputHeadersCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableGenerationButton)
                    .addComponent(mfGenerationButton)
                    .addComponent(uploadIntoDBButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consoleDisplayScrollPane)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consoleDisplayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void outputHeadersCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputHeadersCheckBoxActionPerformed
        // TODO add your handling code here:
        ConfigurationManager.getConfigurationManager().getGTConfiguration().setWithHeader(outputHeadersCheckBox.isSelected());
    }//GEN-LAST:event_outputHeadersCheckBoxActionPerformed

    private void tableGenerationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableGenerationButtonActionPerformed
        // TODO add your handling code here:
        if (validateGTFilePath()) {
            setupFileConfiguration(ConfigurationManager.getConfigurationManager().getGTConfiguration(), filePathTextField.getText());
            TableCreater tc = new TableCreater(consoleDisplayTextArea);
            tc.createAllDBTables();
        }
    }//GEN-LAST:event_tableGenerationButtonActionPerformed

    private void mfPathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfPathButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Choose dataset directory");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            System.out.println("getCurrentDirectory(): " + chooser.getCurrentDirectory());
            System.out.println("getSelectedFile() : " + chooser.getSelectedFile().getPath());
            filePathTextField.setText(chooser.getSelectedFile().getPath());
        } else {
            System.out.println("No Selection");
        }
    }//GEN-LAST:event_mfPathButtonActionPerformed

    private void mfGenerationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfGenerationButtonActionPerformed
        // TODO add your handling code here:
        if (validateMFFilePath()) {
            setupFileConfiguration(ConfigurationManager.getConfigurationManager().getMFConfiguration(), filePathTextField.getText());
            MasterFileCreater mfc = new MasterFileCreater(consoleDisplayTextArea);
            mfc.createMasterFile();
        }
    }//GEN-LAST:event_mfGenerationButtonActionPerformed

    private void uploadIntoDBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadIntoDBButtonActionPerformed
        // TODO add your handling code here:
        if (validateDPFilePath()) {
            setupFileConfiguration(ConfigurationManager.getConfigurationManager().getDPConfiguration(), filePathTextField.getText());
            DatabaseTableInserter dti = new DatabaseTableInserter(consoleDisplayTextArea);
            dti.insertIntoDatabase();
        }
    }//GEN-LAST:event_uploadIntoDBButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane consoleDisplayScrollPane;
    private javax.swing.JTextArea consoleDisplayTextArea;
    private javax.swing.JTextField filePathTextField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton mfGenerationButton;
    private javax.swing.JButton mfPathButton;
    private javax.swing.JCheckBox outputHeadersCheckBox;
    private javax.swing.JButton tableGenerationButton;
    private javax.swing.JButton uploadIntoDBButton;
    // End of variables declaration//GEN-END:variables
}
